import {Color, Matrics, Fonts, ApplicationStyles} from '../../common/styles';

export default styles = {
  systemNotProtectedView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: Matrics.screenWidth - 20,
    shadowOffset: {width: 2, height: 0},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    borderRadius: 10,
    margin: 10,
    backgroundColor: '#fff',
    padding: 10,
    minHeight: 280,
  },
  shieldHeight: {width: 80, height: 100},
  scanTouch: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  signatureVerifyScreen: {
    position: 'absolute',
    zIndex: 1,
    height: 30,
    width: 30,
    top: 5,
    right: 5,
    alignItems: 'center',
  },
  shildImgeView: {
    height: 220,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  subView: {
    width: '100%',
    alignItems: 'center',
  },
  registerText: {
    color: Color.error,
    fontSize: 16,
  },
  simpleText: {
    color: Color.black,
    fontSize: 16,
    textAlign: 'center',
  },
  simpleBoldText: {
    fontWeight: 'bold',
    color: Color.green,
    textDecorationLine: 'underline',
  },
  systemProtectedView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: Matrics.screenWidth - 40,
    shadowOffset: {width: 2, height: 0},
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    borderRadius: 10,
    margin: 10,
    backgroundColor: '#fff',
    padding: 5,
    minHeight: 290,
  },
  protectionText: {
    fontSize: Matrics.ScaleValue(16),
    color: Color.black,
    marginTop: Matrics.ScaleValue(10),
    textAlign: 'center',
  },
  serviceText: {
    fontSize: Matrics.ScaleValue(16),
    color: Color.black,
    marginTop: Matrics.ScaleValue(10),
    textAlign: 'center',
  },
  protectionConditionText: {
    fontSize: Matrics.ScaleValue(9.5),
    color: '#000',
    textAlign: 'center',
  },
  shildIconView: {marginTop: 5, height: 100},
  editSystemTouch: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  systemNameText: {
    fontSize: Matrics.ScaleValue(16),
    color: '#000',
    textAlign: 'center',
    marginTop: 0,
    textDecorationLine: 'underline',
  },
  systemTagText: {
    fontSize: Matrics.ScaleValue(16),
    color: '#000',
    textAlign: 'center',
  },
  animateCircleView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  protectedDTSubView: {
    width: Matrics.screenWidth / 6,
    height: Matrics.screenWidth / 6,
    marginHorizontal: Matrics.screenWidth * 0.01,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  dayNumber: {
    fontSize: 12,
    color: '#000',
    textAlign: 'center',
  },
  dayText: {
    fontSize: 12,
    color: '#000',
  },
  textdescView: {
    marginTop: 5,
  },
  textdesc: {
    fontSize: 10,
  },
  tcTextView: {
    borderWidth: 3,
    position: 'absolute',
    width: Matrics.screenWidth / 7,
    height: Matrics.screenWidth / 7,
    borderRadius: Matrics.screenWidth / 14,
    borderColor: 'red',
  },
  complaintListButton: {
    margin: 5,
    backgroundColor: Color.primary,
    padding: 5,
    width: '90%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
  },
  complaintText: {
    color: '#fff',
    fontSize: Matrics.ScaleValue(12),
  },
};
