import {Color, Matrics, Fonts, ApplicationStyles} from '../../common/styles';

export default styles = {
  ...ApplicationStyles,
  safeAreaView: {
    flex: 1,
    backgroundColor: '#fff',
  },
  validationView: {
    position: 'absolute',
    zIndex: 1,
    top: 50,
    left: 0,
    justifyContent: 'center',
    width: '100%',
    height: 50,
    backgroundColor: '#fff',
    borderColor: '#ccc',
    borderBottomWidth: 1,
  },
  errorClass: {textAlign: 'center', color: 'red'},
  imageViewClass: {
    height: Matrics.ScaleValue(120),
    width: Matrics.ScaleValue(120),
    backgroundColor: '#d3d3d3',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Matrics.ScaleValue(120) / 2,
  },
  editTouchClass: {
    position: 'absolute',
    zIndex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    padding: 10,
    borderRadius: 20,
  },
  formGroup: {flex: 1, padding: 10},
  birthdayForm: {
    height: 50,
    flex: 1,
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomColor: '#d3d3d3',
    borderBottomWidth: 1,
  },
  birthdayLabel: {width: 120, paddingLeft: 5},
  birthdayLabelText: {color: '#333', fontSize: 14},
  datePickerView: {
    flex: 1,
    justifyContent: 'flex-start',
  },
  genderForm: {
    width: '100%',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderColor: '#ccc',
    height: 60,
    alignItems: 'center',
  },
  genderLabelView: {
    height: 60,
    justifyContent: 'center',
    width: 120,
    paddingLeft: 5,
  },
  genderPicker: {height: 50, width: 200, marginLeft: -5},
  labelClass: {
    borderBottomWidth: 1,
    borderColor: '#d3d3d3',
    flexDirection: 'row',
    height: 60,
    alignItems: 'center',
  },
  width120: {width: 120},
  font16_333: {
    color: '#333',
    fontSize: 16,
  },
  font16_999: {color: '#999', fontSize: 16},
  subTextBoxView: {
    width: '100%',
    borderBottomWidth: 1,
    borderBottomColor: '#d3d3d3',
  },
  userView: {
    height: Matrics.ScaleValue(120),
    width: Matrics.screenWidth,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
  },
  userImage: {
    height: Matrics.ScaleValue(120),
    width: Matrics.ScaleValue(120),
    borderRadius: Matrics.ScaleValue(120) / 2,
  },
  customStyle: {
    paddingLeft: 0,
    marginLeft: 0,
  },
};
