import {Color, Matrics} from '../../common/styles';

export default styles = {
  container: {
    flex: 1,
    backgroundColor: Color.white,
  },
  txtStyle2: {
    color: Color.charcoalGrey,
    textAlign: 'center',
    fontSize: Matrics.ScaleValue(17),
  },
  txtStyle3: {
    color: Color.charcoalGrey,
    fontSize: Matrics.ScaleValue(14),
    alignSelf: 'center',
    marginLeft: Matrics.ScaleValue(5),
  },
  txtStyle4: {
    color: Color.charcoalGrey,
    fontSize: Matrics.ScaleValue(14),
    alignSelf: 'center',
  },
  txtStyle5: {
    fontSize: Matrics.ScaleValue(15),
    color: Color.charcoalGrey,
  },
  txtStyle6: {
    fontSize: Matrics.ScaleValue(15),
    color: Color.orangish,
  },
  checkboxStyle: {
    color: Color.white,
    backgroundColor: Color.charcoalGrey,
    borderColor: Color.charcoalGrey,
    borderRadius: Matrics.ScaleValue(2),
  },
  imageStyle: {
    alignSelf: 'center',
  },
  txtfieldStyle: {
    paddingTop: Matrics.ScaleValue(9),
  },
  backgroundImageStyle: {
    width: '100%',
    height: Matrics.ScaleValue(55),
    justifyContent: 'center',
  },
  remberpwdView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  loginText: {
    color: Color.WHITE,
    fontSize: Matrics.ScaleValue(18),
    fontWeight: 'bold',
  },
  fbLoginText: {
    color: Color.darkGreyBlue,
    fontSize: Matrics.ScaleValue(18),
    fontWeight: 'bold',
  },
  signupLinkText: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: Matrics.ScaleValue(14),
  },
  textBoxView: {flex: 1, justifyContent: 'flex-start', alignItems: 'center'},
  subTextBoxView: {
    width: '80%',
    borderBottomWidth: 1,
    borderBottomColor: '#d3d3d3',
  },
  subRadioBoxView: {
    width: '80%',
    borderBottomWidth: 1,
    borderBottomColor: '#d3d3d3',
    flexDirection: 'row',
    height: 50,
    alignItems: 'center',
  },
  floatingView: {
    margin: 10,
    backgroundColor: Color.primary,
    borderRadius: 25,
    height: 50,
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  forgotRememberView: {
    flexDirection: 'row',
    height: 20,
    justifyContent: 'space-between',
    width: '80%',
    marginTop: 5,
  },
  rememberView: {
    flexDirection: 'row',
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  loginView: {height: 40, width: '60%', marginTop: 15, alignItems: 'center'},
  touchableLogin: {
    backgroundColor: '#393184',
    width: 120,
    height: 40,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginText: {color: '#fff', fontSize: 16, fontWeight: 'bold'},
  dontAccountView: {flex: 1, flexDirection: 'row', marginTop: 5},
  touchDontAccount: {justifyContent: 'center', flexDirection: 'row'},
  dontAccText: {color: '#000', fontSize: 14},
  createAccText: {color: '#393184', fontSize: 14},
  lastLineScreen: {
    height: 30,
    width: '100%',
    position: 'absolute',
    zIndex: 1,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#e5e5e5',
    flexDirection: 'row',
    paddingHorizontal: 10,
  },
  errorView: {
    height: 15,
    justifyContent: 'center',
    width: '100%',
    alignItems: 'flex-start',
    width: '80%',
  },
  errorText: {
    fontSize: 14,
    color: 'red',
  },
  spinnerView: {
    flex: 1,
    justifyContent: 'center',
    alignSelf: 'center',
  },
};
